function createfigureNS(X1, Y1, Y2)
%CREATEFIGURE(X1, Y1, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 14-Aug-2016 23:33:28

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,...
    'YColor',[0 0 1],...
    'FontSize',16);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1 3]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.0001 0.0011]);
box(axes1,'on');
hold(axes1,'on');

% Create plot
plot(X1,Y1,'Parent',axes1,'MarkerFaceColor',[0 0 1],'MarkerSize',15,...
    'Marker','square',...
    'LineWidth',2,...
    'Color',[0 0 1]);

% Create axes
axes2 = axes('Parent',figure1,'HitTest','off','Color','none',...
    'YColor',[1 0 0],...
    'YAxisLocation','right',...
    'FontSize',16);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[1 3]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0 1]);
hold(axes2,'on');

% Create plot
plot(X1,Y2,'Parent',axes2,'MarkerFaceColor',[1 0 0],'MarkerSize',15,...
    'Marker','o',...
    'LineWidth',2,...
    'Color',[1 0 0]);
title('Average Silhouette (red) vs. Reconstruction (blue)');

